using Cynara.Domain.Tasks;

namespace Cynara.Application.Modules.Tasks.Persistence;

/// <summary>
/// Persistence port for clinical tasks. All read paths are hospital-scoped.
/// Write operations return tracked entities the workflows can mutate without
/// committing; the unit-of-work boundary is owned by the workflow, not by
/// the repository.
/// </summary>
public interface ITaskRepository
{
    /// <summary>
    /// Returns the task matching the supplied identifier in the resolved
    /// hospital workspace, or <see langword="null"/> when no record exists.
    /// Terminal states remain resolvable.
    /// </summary>
    public Task<ClinicalTask?> FindByIdAsync(
        Guid hospitalId,
        Guid id,
        bool track,
        CancellationToken cancellationToken);

    /// <summary>
    /// Lists tasks in the resolved hospital workspace that match the
    /// supplied filter. Terminal states are included by default.
    /// </summary>
    public Task<IReadOnlyList<ClinicalTask>> ListAsync(
        Guid hospitalId,
        TaskListCriteria criteria,
        CancellationToken cancellationToken);

    /// <summary>
    /// Lists open (open or claimed) tasks for one encounter that reference
    /// the supplied form code. Used to close tasks when the referenced
    /// clinical document completes.
    /// </summary>
    public Task<IReadOnlyList<ClinicalTask>> ListOpenByFormCodeAsync(
        Guid hospitalId,
        Guid encounterId,
        string formCode,
        bool track,
        CancellationToken cancellationToken);

    /// <summary>
    /// Lists open (open or claimed) tasks generated by the supplied
    /// pipeline. Used to cancel outstanding work when the pipeline
    /// terminates.
    /// </summary>
    public Task<IReadOnlyList<ClinicalTask>> ListOpenByPipelineAsync(
        Guid hospitalId,
        Guid pipelineId,
        bool track,
        CancellationToken cancellationToken);

    /// <summary>Adds a new task to the change tracker.</summary>
    public void Add(ClinicalTask task);
}

/// <summary>
/// Filter criteria for the task list endpoint. All fields are optional;
/// a fully empty criteria returns the hospital task roster.
/// </summary>
public sealed record TaskListCriteria(
    ClinicalTaskStatus? Status,
    Guid? PatientId = null,
    Guid? EncounterId = null,
    Guid? PipelineId = null,
    string? AssignedActor = null,
    string? AssignedRole = null,
    string? AssignedDiscipline = null);
