using Cynara.Api.Common.ActorContext;
using Cynara.Application.Modules.Tasks;
using Cynara.Domain.Capabilities;

namespace Cynara.Api.Modules.Tasks;

/// <summary>
/// HTTP surface for the clinical task runtime. Tasks are generated by the
/// pipeline runtime from published workflow definitions; this surface lists
/// and transitions them. All routes are hospital-scoped and capability-gated;
/// the service layer re-checks capabilities so denial never leaks resource
/// existence.
/// </summary>
internal static class TasksEndpoints
{
    public static IEndpointRouteBuilder MapTasksEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        RouteGroupBuilder tasks = endpoints
            .MapGroup("/api/tasks")
            .WithTags("Tasks");

        _ = tasks.MapGet("/", ListTasksAsync)
            .RequireAuthorization(CapabilityCodes.TasksRead)
            .WithName("ListTasks")
            .WithSummary("List clinical tasks in the hospital workspace")
            .Produces<TaskListResponse>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status403Forbidden);

        _ = tasks.MapGet("/{id:guid}", GetTaskAsync)
            .RequireAuthorization(CapabilityCodes.TasksRead)
            .WithName("GetTask")
            .WithSummary("Get one clinical task")
            .Produces<TaskDto>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status403Forbidden)
            .Produces(StatusCodes.Status404NotFound);

        _ = tasks.MapPost("/{id:guid}/claim", ClaimTaskAsync)
            .RequireAuthorization(CapabilityCodes.TasksWrite)
            .WithName("ClaimTask")
            .WithSummary("Claim an open clinical task")
            .Produces<TaskDto>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status400BadRequest)
            .Produces(StatusCodes.Status403Forbidden)
            .Produces(StatusCodes.Status404NotFound)
            .Produces(StatusCodes.Status409Conflict);

        _ = tasks.MapPost("/{id:guid}/complete", CompleteTaskAsync)
            .RequireAuthorization(CapabilityCodes.TasksWrite)
            .WithName("CompleteTask")
            .WithSummary("Complete an open or claimed clinical task")
            .Produces<TaskDto>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status400BadRequest)
            .Produces(StatusCodes.Status403Forbidden)
            .Produces(StatusCodes.Status404NotFound)
            .Produces(StatusCodes.Status409Conflict);

        _ = tasks.MapPost("/{id:guid}/cancel", CancelTaskAsync)
            .RequireAuthorization(CapabilityCodes.TasksWrite)
            .WithName("CancelTask")
            .WithSummary("Cancel an open or claimed clinical task")
            .Produces<TaskDto>(StatusCodes.Status200OK)
            .Produces(StatusCodes.Status400BadRequest)
            .Produces(StatusCodes.Status403Forbidden)
            .Produces(StatusCodes.Status404NotFound)
            .Produces(StatusCodes.Status409Conflict);

        return endpoints;
    }

    private static async Task<IResult> ListTasksAsync(
        string? status,
        Guid? patientId,
        Guid? encounterId,
        Guid? pipelineId,
        string? assignedActor,
        string? assignedRole,
        string? assignedDiscipline,
        ITaskService tasks,
        CancellationToken cancellationToken)
    {
        TaskListResponse response = await tasks.ListAsync(
            new TaskListRequest(
                status,
                patientId,
                encounterId,
                pipelineId,
                assignedActor,
                assignedRole,
                assignedDiscipline),
            cancellationToken).ConfigureAwait(false);
        return Results.Ok(response);
    }

    private static async Task<IResult> GetTaskAsync(
        Guid id,
        ITaskService tasks,
        CancellationToken cancellationToken)
    {
        TaskDto dto = await tasks.GetAsync(id, cancellationToken)
            .ConfigureAwait(false);
        return Results.Ok(dto);
    }

    private static async Task<IResult> ClaimTaskAsync(
        Guid id,
        ClaimTaskRequest request,
        ITaskService tasks,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        TaskDto dto = await tasks.ClaimAsync(
            id,
            request,
            http.GetActorId(),
            cancellationToken).ConfigureAwait(false);
        return Results.Ok(dto);
    }

    private static async Task<IResult> CompleteTaskAsync(
        Guid id,
        TransitionTaskRequest request,
        ITaskService tasks,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        TaskDto dto = await tasks.CompleteAsync(
            id,
            request,
            http.GetActorId(),
            cancellationToken).ConfigureAwait(false);
        return Results.Ok(dto);
    }

    private static async Task<IResult> CancelTaskAsync(
        Guid id,
        TransitionTaskRequest request,
        ITaskService tasks,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        TaskDto dto = await tasks.CancelAsync(
            id,
            request,
            http.GetActorId(),
            cancellationToken).ConfigureAwait(false);
        return Results.Ok(dto);
    }
}
